---
# Server Certificate Example (Generated and Managed by service-ca Controller)
apiVersion: v1
kind: Secret
metadata:
  name: my-service-secret
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: my-service-secret
  namespace: my-namespace
data:
  tls.crt: <base64-encoded-server-certificate>
  tls.key: <base64-encoded-private-key>
---
# Service CA Certificate Public keys
# Per :
# Verificare che il certificato del server sia stato emesso da una CA di cui si fidano.
# Stabilire la fiducia senza accedere direttamente alla chiave privata del server.

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  namespace: my-namespace
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIID...<Service CA Certificate>...
    -----END CERTIFICATE-----
